### ISSUE TITLE
Deformable-3D-Gaussian

### ISSUE THREAD

**Issue by ingra14m** [MrNeRF/awesome-3D-gaussian-splatting#1]
Hi, thanks for your awesome repo.

If you could include [Deformable-Gaussian](https://github.com/ingra14m/Deformable-3D-Gaussians) in chronological order, I would be very grateful. 

This is the first work (on 22 Sep 2023) based on 3D-Gaussian for monocular dynamic scenes and 4D Gaussian also cited my work. The results on the D-NeRF dataset are SOTA.

This is the [arXiv link](https://arxiv.org/abs/2309.13101). However, for some unknown reason, my work and homepage are hard to find on Google search.

Lastly, in fact, the arXiv timestamp for gsgen is earlier than DreamGaussian. It's just that it was open-sourced on GitHub one day later than DreamGaussian. Thank you for your work!

**Comment by MrNeRF** [comment]
Done! Thank you. I hope it is complete for now. I also fixed the order.
Any plans when you release the code? So far, its only the skeleton, isn't it?

**Comment by ingra14m** [comment]
Hello, thank you for your prompt reply! 

The complete code will be open-sourced at the end of this month, and we are currently going through ByteDance's open-source process. However, if you really need the source code, I can send it to you via email for academic purposes. My email address is [here](14ziyiyang@gmail.com).

**Comment by MrNeRF** [comment]
Thx for this kind offer. Currently I don't have much spare time. If that changes, I would contact you. Otherwise I will wait for the official release. In that case make sure to ping me so I can update the status of the link to your repo.

**Comment by ingra14m** [comment]
Hi, full code for Deformable-Gaussian has released.

**Comment by MrNeRF** [comment]
Will update. Thx!
