### ISSUE TITLE
New Gaussian Splatting avatar synthesis method

### ISSUE THREAD

**Issue by Florian-Barthel** [MrNeRF/awesome-3D-gaussian-splatting#112]
Hey,

I am currently working on a method to generate 3D Gaussian Splatting head avatars from a latent space. I would be very happy if my project is listed here as well. 

Paper preprint (accepted at CVPRW): https://arxiv.org/abs/2404.10625
Project page: https://florian-barthel.github.io/gaussian_decoder/index.html
Code: https://github.com/fraunhoferhhi/gaussian_gan_decoder

**Comment by MrNeRF** [comment]
Thx, added!
