### ISSUE TITLE
Addition of gaussian splatting work without a paper?

### ISSUE THREAD

**Issue by An-u-rag** [MrNeRF/awesome-3D-gaussian-splatting#122]
Hi, I recently worked on a project involving stylization of gaussians during optimization of parameters. I was wondering if it could be included here without a paper / publication.

[Github ](https://github.com/An-u-rag/stylized-gaussian-splatting)
[Project Report](https://drive.google.com/file/d/1fRjbJNxb7bWjJ5SW4sE83FDrJ-TaqzG7/view?usp=sharing)

**Comment by MrNeRF** [comment]
Hey,
a paper is not necessary. Interesting work!
There is the other section under "Open Source Implementations". Feel free to submit a pr to include it there.

**Comment by An-u-rag** [comment]
Will do, thanks!
