### ISSUE TITLE
Update of the paper 

### ISSUE THREAD

**Issue by seoha-kim** [MrNeRF/awesome-3D-gaussian-splatting#160]
Hello. Thanks for your earlier listing. 😃
Our work 'Per-Gaussian Embedding-Based Deformation for Deformable 3D Gaussian Splatting' was accepted ECCV 2024. 
Plus, the contents of the abstact were changed after the camera-ready.
Can you update this ? :)

**Comment by MrNeRF** [comment]
Hey, thanks for your issue and sorry for my late response. It would be currently helpful if you could create a pr to update your paper.
Thank you!
