### ISSUE TITLE
Could you help to add our video?

### ISSUE THREAD

**Issue by JiahuiLei** [MrNeRF/awesome-3D-gaussian-splatting#19]
Thanks for your effort in maintaining this useful repo, could you please add the short presentation link of our paper GART? https://www.youtube.com/watch?v=-xYNtIlW4WY
thank you

**Comment by MrNeRF** [comment]
Hey sure. Can you please make a pr? Then I can merge it.

**Comment by MrNeRF** [comment]
I have added it!
