### ISSUE TITLE
Add work Gaussian Grouping

### ISSUE THREAD

**Issue by lkeab** [MrNeRF/awesome-3D-gaussian-splatting#22]
Hi, thanks for your great repo resource! Can you add our new work Gaussian Grouping in it? It is designed for joint reconstruction, segmentation and editing anything in the open-world 3D scene, via lifting SAM.

ArXiv:  https://arxiv.org/abs/2312.00732
Github:  https://github.com/lkeab/gaussian-grouping
Affiliation: ETH Zurich

**Comment by lkeab** [comment]
hi, the code for Gaussian Grouping is ready now. Thanks for your help.

**Comment by MrNeRF** [comment]
Cool, thx
