### ISSUE TITLE
Besides paper summaries, will additional resources like data, courses, and blogs be added later

### ISSUE THREAD

**Issue by NHMMing** [MrNeRF/awesome-3D-gaussian-splatting#224]
Hello, thank you for your sharing. Besides paper summaries, will additional resources like data, courses, and blogs be added later? I noticed they are listed in the table of contents, but the actual content is still empty for now.

**Comment by MrNeRF** [comment]
The rendering of the repo is buggy due to the limited capabilities of github. Either look at the raw Readme.md or checkout the repo and read it locally. It is all there!

**Comment by NHMMing** [comment]
> The rendering of the repo is buggy due to the limited capabilities of github. Either look at the raw Readme.md or checkout the repo and read it locally. It is all there!

got it! thx!
