### ISSUE TITLE
Add a gaussian head work

### ISSUE THREAD

**Issue by chiehwangs** [MrNeRF/awesome-3D-gaussian-splatting#23]
Hi,

Thank you for maintaining this excellent library！

Our latest 3D Gaussian based work has been announced, can it be added to this library? We built a refined head avatar based on dynamic explicit structures.

arXiv:  [https://arxiv.org/abs/2312.01632](https://arxiv.org/abs/2312.01632)
github: [https://github.com/chiehwangs/gaussian-head](https://github.com/chiehwangs/gaussian-head)

best,
chieh

**Comment by MrNeRF** [comment]
Thank you. We will add your and the other new research later today

**Comment by henrypearce4D** [comment]
Added, thankyou!
