### ISSUE TITLE
Add a gaussian avatar work

### ISSUE THREAD

**Issue by huliangxiao** [MrNeRF/awesome-3D-gaussian-splatting#24]
Hi! Thank you for providing the awesome library! 

Our latest Gaussian-based work for avatar modeling has been announced, and we would greatly appreciate it if you could add it to your library.

Project: https://huliangxiao.github.io/GaussianAvatar
arXiv: https://arxiv.org/abs/2312.02134
github: https://github.com/huliangxiao/GaussianAvatar

best,
liangxiao

**Comment by MrNeRF** [comment]
done!
