### ISSUE TITLE
Request to update the paper link

### ISSUE THREAD

**Issue by alvinliu0** [MrNeRF/awesome-3D-gaussian-splatting#25]
Hi: 

Thank you for maintaining such an awesome library! Could you please kindly update the paper link for "HumanGaussian: Text-Driven 3D Human Generation with Gaussian Splatting"? For better accessibility, I guess it would be better to provide an arxiv link:

Paper: https://arxiv.org/pdf/2311.17061.pdf

Thank you so much!

Xian Liu

**Comment by MrNeRF** [comment]
Done!
