### ISSUE TITLE
Request to update the paper link

### ISSUE THREAD

**Issue by ShunyuanZheng** [MrNeRF/awesome-3D-gaussian-splatting#34]
Hi:

Thank you for providing such an awesome library! Could you please kindly update the paper link for 'GPS-Gaussian: Generalizable Pixel-wise 3D Gaussian Splatting for Real-time Human Novel View Synthesis'?

arXiv link: https://arxiv.org/pdf/2312.02155.pdf

Best Regards,

Shunyuan Zheng

**Comment by MrNeRF** [comment]
Thx. Updated!
