### ISSUE TITLE
Add a new paper

### ISSUE THREAD

**Issue by YuyangYin** [MrNeRF/awesome-3D-gaussian-splatting#35]
Could you please add the new 4D generation paper? thanks!

paper name: 4DGen: Grounded 4D Content Generation with Spatial-temporal Consistency
author: Yuyang Yin, Dejia Xu, Zhangyang Wang, Yao Zhao, Yunchao Wei
website：https://vita-group.github.io/4DGen/
paper：https://arxiv.org/abs/2312.17225
code：https://github.com/VITA-Group/4DGen

**Comment by MrNeRF** [comment]
done! thx!
