### ISSUE TITLE
Please add a new paper.

### ISSUE THREAD

**Issue by YuelangX** [MrNeRF/awesome-3D-gaussian-splatting#36]
Title: Gaussian Head Avatar: Ultra High-fidelity Head Avatar via Dynamic Gaussians
author: Yuelang Xu, Benwang Chen, Zhe Li, Hongwen Zhang, Lizhen Wang, Zerong Zheng, Yebin Liu
project page: https://yuelangx.github.io/gaussianheadavatar/
arXiv: https://arxiv.org/abs/2312.03029
code: https://github.com/YuelangX/Gaussian-Head-Avatar

Thank you!

**Comment by MrNeRF** [comment]
Apparently I missed that one. Sorry about that!
It is listed as well now! Thx!
