### ISSUE TITLE
Request to add Gaussian Splat Operators (GSOPs) for SideFX Houdini

### ISSUE THREAD

**Issue by david-rhodes** [MrNeRF/awesome-3D-gaussian-splatting#43]
Hey, great resource you've put together here--thank you! Would you consider adding GSOPs to your list, please? I'd classify it as more of a utility than a viewer.

> Use GSOPs to import, edit, and export gaussian splat models, or generate synthetic training data. Synthetic data is capable of producing high-fidelity models with view-dependent effects, relatively small file sizes, and incredible rendering performance on most modern devices.
> 
> With GSOPs, you can isolate objects or sections, eliminate noise and floaters, deform and animate models, compose scenes, mesh splats, and conduct feature analysis.

Thank you!

https://github.com/david-rhodes/GSOPs

**Comment by henrypearce4D** [comment]
Thanks David, added :)

**Comment by david-rhodes** [comment]
Thank you @henrypearce4D!
