### ISSUE TITLE
Retracted paper for Animatable 3D Gaussians

### ISSUE THREAD

**Issue by dedoubleyou1** [MrNeRF/awesome-3D-gaussian-splatting#45]
It appears the paper for the following (In Avatars -> 2023) has been retracted:
 
3. Animatable 3D Gaussians for High-fidelity Synthesis of Human Motions 

On the [arXiv page](https://arxiv.org/abs/2311.13404) they state the following 

> Some experiment data is wrong. The expression of the paper in introduction and abstract is incorrect. Some graphs have inappropriate descriptions

**Comment by MrNeRF** [comment]
Oh wow. Thank you for bringing this up! I removed it.
