### ISSUE TITLE
One paper does not belong to the diffusion category

### ISSUE THREAD

**Issue by mohammadasim98** [MrNeRF/awesome-3D-gaussian-splatting#46]
Hi,

I read the paper from "Triplane Meets Gaussian Splatting: Fast and Generalizable Single-View 3D Reconstruction with Transformers" listed as number 10 in the diffusion category and it does not seems to belong to the generative approaches rather should belong to the pure reconstruction approach. 

let me know if am missing something. 

thank you.

**Comment by MrNeRF** [comment]
Thx, I will look into it,
