### ISSUE TITLE
Inclusion Request for Customizable SLAM Robustness Benchmark (Gaussian Splatting vs NeRF representation for instant 3D reconstruction and localization)

### ISSUE THREAD

**Issue by Xiaohao-Xu** [MrNeRF/awesome-3D-gaussian-splatting#59]
Hey guys,

We sincerely appreciate the value of your repository! We would like to kindly request the inclusion of our **customizable SLAM robustness benchmark**, which incorporates a noisy data simulation pipeline for a comprehensive evaluation of SLAM performance. 

Our benchmark mainly focuses on **evaluating the robustness of the latest monocular/multi-modal Neural-based SLAM models**, including **NeRF-based and Gaussian-Splatting-based** SLAM, which reveals **GS representation is more robust than NeRF representation under sensor corruptions** for instant 3D reconstruction and localization. 

We greatly appreciate your consideration. Thanks!

* **Customizable-SLAM**: Customizable Perturbation Synthesis for Robust SLAM Benchmarking, ArXiV, 2024. [[Paper](https://arxiv.org/abs/2402.08125)] [[Code](https://github.com/Xiaohao-Xu/SLAM-under-Perturbation)] [[Video](https://www.youtube.com/watch?v=jNM94naSPXA)]

**Comment by MrNeRF** [comment]
Hey, 
thanks for the ping. Might be a valuable addition. I am a bit hesitant because I would say it is very strongly tied to SLAM in general and less specific to gaussian splatting. 
I have thought about adding a data category. What do you think were this would fit best in?

**Comment by Xiaohao-Xu** [comment]
Sure thing! I think it would be awesome to add a new category 'Data' or 'Benchmark.' It'll make things easier to find and organize.

**Comment by MrNeRF** [comment]
Ok great, I will add it over the weekend!

**Comment by MrNeRF** [comment]
I introduced a data section. But I think it is better to link it when it is published. Otherwise I don't see much of value here as it is also not very specific to 3DGS. Please ping me when you have uploaded the dataset.
