### ISSUE TITLE
Please add a new paper

### ISSUE THREAD

**Issue by renhaofan** [MrNeRF/awesome-3D-gaussian-splatting#61]
Title: GaussianPro: 3D Gaussian Splatting with Progressive Propagation
author: Kai Cheng, Xiaoxiao Long, Kaizhi Yang, Yao Yao, Wei Yin, Yuexin Ma, Wenping Wang, Xuejin Chen
arXiv:  https://arxiv.org/pdf/2402.14650.pdf

Thank you!

**Comment by MrNeRF** [comment]
Done!
