### ISSUE TITLE
MIT Lecture on gaussian splatting

### ISSUE THREAD

**Issue by cs-mshah** [MrNeRF/awesome-3D-gaussian-splatting#63]
It would be great if this course could be included in the tutorials/blogs: https://www.scenerepresentations.org/courses/inverse-graphics-23  

The last lecture of module 2 contains an overview of Gaussian Splatting.

**Comment by MrNeRF** [comment]
That's really great. I will add this. Thanks for this link!

**Comment by MrNeRF** [comment]
Added. Thanks again!
