### ISSUE TITLE
New 3DGS Viewer

### ISSUE THREAD

**Issue by Florian-Barthel** [MrNeRF/awesome-3D-gaussian-splatting#65]
Hey, 
thank you for your awesome summary of current 3DGS methods!

I'm currently working on an interactive viewer for 3D Gaussian Splatting objects that is fully written in python. I hope that this project can contribute for understanding and debugging 3DGS methods.
I would feel honored to be  mentioned in your list.

https://github.com/Florian-Barthel/gaussian_viewer

Thank you!

**Comment by MrNeRF** [comment]
Cool. Loads even Compact3D plys. Will add it later today or tomorrow.

**Comment by MrNeRF** [comment]
Done!
