### ISSUE TITLE
Incorrect arxiv link

### ISSUE THREAD

**Issue by cs-mshah** [MrNeRF/awesome-3D-gaussian-splatting#67]
I believe the arxiv link to https://github.com/MrNeRF/awesome-3D-gaussian-splatting?tab=readme-ov-file#9-dreamscene-3d-gaussian-based-text-to-3d-scene-generation-via-formation-pattern-sampling is incorrect. Their project page says that they're yet to release the paper.

**Comment by MrNeRF** [comment]
Yes. You are right. Thank you. I fixed it. I guess this paper will be release either by tomorrow or next week.

**Comment by cs-mshah** [comment]
Excited for its paper and code release!
