### ISSUE TITLE
Add a new paper

### ISSUE THREAD

**Issue by slothfulxtx** [MrNeRF/awesome-3D-gaussian-splatting#69]
Thank you for your contribution to all the researchers on 3D-GS. We've just finished a new work on 3D-GS, focusing on disentangling the geometry and appearance for 3D-GS. Could you add it to the repo? Thanks!

paper name: Texture-GS: Disentangling the Geometry and Texture for 3D Gaussian Splatting Editing
website：https://slothfulxtx.github.io/TexGS/
paper：https://arxiv.org/abs/2403.10050
code(coming soon)：https://github.com/slothfulxtx/Texture-GS

**Comment by MrNeRF** [comment]
So many papers were released. I would appreciate if you could submit a pr. Thx.

**Comment by MrNeRF** [comment]
I already got it added.
