### ISSUE TITLE
Please add NEDS-SLAM in SLAM section, thanks !

### ISSUE THREAD

**Issue by JimOriginal** [MrNeRF/awesome-3D-gaussian-splatting#73]
https://arxiv.org/abs/2403.11679

**Comment by MrNeRF** [comment]
So many papers were released. I would appreciate if you could submit a pr. Thx.

**Comment by MrNeRF** [comment]
Ok, got it already added.

**Comment by Atticuszz** [comment]
@MrNeRF did u read that paper?i even not seen the code and the picture of Experimental results，and how do him prove that is true? and it's so similar to [`Splatam`](https://github.com/spla-tam/SplaTAM)

**Comment by JimOriginal** [comment]
I sincerely apologise that the current version of the paper only includes validation images from a few scenes. We will endeavour to supplement more comprehensive experimental data, including additional photographs and detailed tables, as soon as possible to better demonstrate the efficacy of NEDS-SLAM.

**Comment by Atticuszz** [comment]
> @Atticuszz I sincerely apologise that the current version of the paper only includes validation images from a few scenes. We will endeavour to supplement more comprehensive experimental data, including additional pictures and detailed tables, as soon as possible to better demonstrate the efficacy of NEDS-SLAM.

wait for your great work
