### ISSUE TITLE
Label Publications, e.g., CVPR, ArXiv

### ISSUE THREAD

**Issue by Gaozhongpai** [MrNeRF/awesome-3D-gaussian-splatting#79]
As the title says

**Comment by henrypearce4D** [comment]
thanks for the suggestion, do you have any spare time to help with this?

**Comment by MrNeRF** [comment]
I am also not able to do this currently. But it would be a nice addition. If you have time and want to contribute, we would really appreciate it . Feel free to create a pr. I will close this issue for now.
