### ISSUE TITLE
Incorrect project page link

### ISSUE THREAD

**Issue by ShunyuanZheng** [MrNeRF/awesome-3D-gaussian-splatting#95]
Hi, 

The project page link of "GPS-Gaussian: Generalizable Pixel-wise 3D Gaussian Splatting for Real-time Human Novel View Synthesis" is incorrect, and it should be https://shunyuanzheng.github.io/GPS-Gaussian.

Could you kindly update the info? Thanks!

**Comment by MrNeRF** [comment]
Thx, is updated!
